### ISSUE TITLE
64bit requirement error

### ISSUE THREAD

**Issue by Bhagsa123** [MeghaPatel2022/Video-Player#1]

**Comment by MeghaPatel2022** [comment]
Please send me the error log and testing device description

**Comment by Bhagsa123** [comment]
This module generating only 32bit code 
Video-Player/giraffeplayer2/build.gradle

Due to this code its generating only 32-bit libraries you can remove it to support 64 bit devices

if ("" == bType) {
        api "com.github.tcking:ijkplayer-armv7a:${ijkVersion}"
    } else if ("full" == bType) {
        api "com.github.tcking:ijkplayer-armv7a:${ijkVersion}-full"
    }

You can check this reference here https://developer.android.com/distribute/best-practices/develop/64-bit
